// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWtx2uLfJXt5zc3-IqFWLsClV6Q0Od-g',
    appId: '1:1078813120283:web:3ca2ebeaf2972d2407a5be',
    messagingSenderId: '1078813120283',
    projectId: 'sofi-saint-app',
    authDomain: 'sofi-saint-app.firebaseapp.com',
    storageBucket: 'sofi-saint-app.firebasestorage.app',
    measurementId: 'G-MG7C2VB857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArA0oKMWs_Ic4yZUdKgXu_xNFjt1yFnAA',
    appId: '1:1078813120283:android:6415bbd68eba960107a5be',
    messagingSenderId: '1078813120283',
    projectId: 'sofi-saint-app',
    storageBucket: 'sofi-saint-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOu0fNeXadngEoJCyeUsnAtCcGbw1Rkc',
    appId: '1:1078813120283:ios:d6cd1d3850138cbc07a5be',
    messagingSenderId: '1078813120283',
    projectId: 'sofi-saint-app',
    storageBucket: 'sofi-saint-app.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
